### ISSUE TITLE
`navigator.getInstalledRelatedApps()` doesn't detecting the installed app

### ISSUE THREAD

**Issue by MrZhouZh** [benfredwells/get-installed-related-apps#33]
I've been trying to implement the getInstalledRelatedApps API to work into my project, but the relatedApps as shown below is returning empty. 

Here is the code demo link: https://codesandbox.io/s/7fz9kb. 

The playstore app ID has been doublechecked from the android app side. any help would be appreciated, thanks!

![image](https://user-images.githubusercontent.com/24643748/170399636-6f41d42b-1bc7-4325-bc6a-761efe4139fe.png)

**Comment by rayankans** [comment]
This repo is for specification/standardization issues. If you have a bug please file against individual browsers (I believe that would be crbug.com in your case).
